include:
  - board: nice_nano_v2
    shield: zodiark_left
  - board: nice_nano_v2
    shield: zodiark_right
include:
  - board: nice_nano_v2
    shield: zodiark_left
  - board: nice_nano_v2
    shield: zodiark_right
